-- GENERATED by `python -m ml.lp.classify --emit-sql` from ml/lp/classify.py.
-- Do NOT hand-edit: edit SPORT_PREFIXES / MARKET_TYPE_TOKENS there and regenerate.
-- The canonical ticker -> (sport, market_type) taxonomy, shared by every mart so
-- the LP-fills side and the capture side classify identically and their verdicts join.

{% macro classify_sport(col) %}
    case
        when {{ col }} like 'KXWC%' then 'WC'
        when {{ col }} like 'KXMLS%' then 'MLS'
        when {{ col }} like 'KXLIGAMX%' then 'LIGAMX'
        when {{ col }} like 'KXBRASILEIRO%' then 'BRASILEIRO'
        when {{ col }} like 'KXALLSVENSKAN%' or {{ col }} like 'KXELITESERIEN%' or {{ col }} like 'KXDENSUPERLIGA%' then 'SCANDI'
        when {{ col }} like 'KXEPL%' then 'EPL'
        when {{ col }} like 'KXLALIGA%' then 'LALIGA'
        when {{ col }} like 'KXSERIEA%' then 'SERIEA'
        when {{ col }} like 'KXBUNDESLIGA%' then 'BUNDESLIGA'
        when {{ col }} like 'KXLIGUE1%' then 'LIGUE1'
        when {{ col }} like 'KXUCL%' or {{ col }} like 'KXUEL%' then 'UCL_UEL'
        when {{ col }} like 'KXEREDIVISIE%' or {{ col }} like 'KXEFLCHAMPIONSHIP%' or {{ col }} like 'KXCOPADOBRASIL%' or {{ col }} like 'KXSAUDIPL%' then 'SOCCER_OTHER'
        when {{ col }} like 'KXWNBA%' then 'WNBA'
        when {{ col }} like 'KXMLB%' then 'MLB'
        when {{ col }} like 'KXNCAA%' then 'NCAA'
        when {{ col }} like 'KXNBA%' then 'NBA'
        when {{ col }} like 'KXNHL%' then 'NHL'
        when {{ col }} like 'KXNFL%' then 'NFL'
        when {{ col }} like 'KXATP%' then 'ATP'
        when {{ col }} like 'KXITF%' then 'ITF'
        when {{ col }} like 'KXWTA%' then 'WTA'
        else 'OTHER'
    end
{% endmacro %}

{% macro classify_market_type(col) %}
    case
        when {{ col }} like '%TOTAL%' then 'TOTAL'
        when {{ col }} like '%SPREAD%' then 'SPREAD'
        when {{ col }} like '%MATCH%' then 'MATCH'
        when {{ col }} like '%WINNER%' then 'WINNER'
        when {{ col }} like '%GAME%' then 'GAME'
        else 'OTHER'
    end
{% endmacro %}
